### ISSUE TITLE
How to use callable using $args as callback for a route ?

### ISSUE THREAD

**Issue by PhilJung** [PHP-DI/Slim-Bridge#16]
Hi,

In our code, we want to give a class name as target for a route:

  $app->delete('/room/{photo_id:[0-9]+}', '\Actions\Photos\DeletePhotoAction');

The DeletePhotoAction is a class that inherits from GenericAction : 

    abstract class GenericAction {
        public function __invoke(Request $request, Response $response, $args) {
            if ( /* userHasSufficientRights */ ) {
                return $this->execute($request, $response, $args);
            } else {
                // Not good
            }
        }
        public abstract function execute(Request $request, Response $response, $args);
    }

Then all actions simply inherits from GenericAction and overwrite the execute method.

This leads to 

    "/vendor/php-di/invoker/src/Invoker.php" 
    line: 75
    message: "Unable to invoke the callable because no value was given for parameter 3 ($args)"

Seems to be related to ControllerInvoker.php:45  

Changing from 

        // Inject the route arguments by name
        $parameters += $routeArguments;

to 

        // Inject the route arguments by name
        $parameters['args'] = $routeArguments;

is working as (we) expected

Trying to change the generic action to 

    public function __invoke(Request $request, Response $response, ...$args) {

is not acceptable as we need to forward this to execute and then the method signature is variable in child classes. 

What would be your recommended way to manage this ?

Philippe

**Comment by mnapoli** [comment]
Hi Philippe, regarding the different points:

- using a base controller class that redirects to other methods is not a very good solution IMO, and it's not compatible with this bridge. I would encourage you to verify user authorization [using middlewares instead](https://www.slimframework.com/docs/concepts/middleware.html) (because that's exactly what middlewares are for)
- the PHP-DI bridge doesn't pass the `$args` parameter, instead parameters are injected directly by name (e.g. in your example you could have a `$photo_id` parameter instead of `$args`). The reason for that is that it's clearer and simpler.

However you can still get those parameters by doing `$request->getAttributes()`, but I would really recommend having a look at middlewares.

Since this is more a question/discussion than a bug or feature I'll mark the issue as "closed" preemptively (because else I end up with open issues all over the projects and important bugs slip by), but please feel free to answer and continue the discussion.

**Comment by PhilJung** [comment]
No problem with closing the issue :-)

Regarding middleware, we are already using middleware for auth (tuupola/slim-basic-auth + homemade LDAPAuthenticator to be precise). This allows us to ensure authentification. Now, we want to deal with authorization (actions can be performed only by people with a given profile) -> maybe route middleware could do the trick.

We are not using a base controller that redirects. We simply declare routes, each route is an action (so more or less a controller), an action is a class and all these classes have a common ancestor. In this ancestor we have a shared behaviour that checks authorization prior to executing the code (in other words, no redirect to another class)

On the other hand, having the parameters explicitly passed as parameters is closer to the DI philosophy than getting them in an array. 

We will look how to change our code so that it works this way.

I close the issue :-)

**Comment by mnapoli** [comment]
:+1: 

> Now, we want to deal with authorization

Absolutely, I mixed authentication and authorization. Authorization can also be done in middlewares (with route middlewares for example as you mention), hopefully it will be a good alternative to you current architecture.

> We are not using a base controller that redirects.

Again you are right :) "forward the call" would have been better than "redirect", but in any case I see what you mean

**Comment by vikkio88** [comment]
I am using the same pattern, with a Callable class with ```__invoke```, to get the ```$args``` with **php-di slim bridge** I do this
```php
private function getArgsFromRequest(RequestInterface $request): array
    {
        $attributes = $request->getAttributes();
        return isset($attributes["route"]) ? ($attributes["route"])->getArguments() : [];
    }

    public function __invoke(RequestInterface $request, ResponseInterface $response): ResponseInterface
    {
        $this->request = $request;
        $this->response = $response;
        $this->args = $this->getArgsFromRequest($request);
        return $this->execute();
    }
```

**Comment by reiniermybeats** [comment]
For anyone finding this thread like me in or after 2022
My route attributes live in `['__route__']` take note of the double underscores before and after.

so the `private function getArgsFromRequest` (from @vikkio88) will become:

```
private function getArgsFromRequest(RequestInterface $request): array
{
    $attributes = $request->getAttributes();
    return isset($attributes["__route__"]) ? ($attributes["__route__"])->getArguments() : [];
}
```
