### ISSUE TITLE
Slim uses unset, can't remove default container items with Slim-Bridge

### ISSUE THREAD

**Issue by adjenks** [PHP-DI/Slim-Bridge#17]
In the slim documentation they say the following:

> Disabling
> To completely disable Slim’s error handling, simply remove the error handler from the container:
> unset($app->getContainer()['errorHandler']);
> unset($app->getContainer()['phpErrorHandler']);

[https://www.slimframework.com/docs/handlers/error.html#disabling](https://www.slimframework.com/docs/handlers/error.html#disabling)

But when you try this with the Slim-Bridge container, it's not a simple array anymore and you get this error:

> PHP Fatal error:  Uncaught Error: Cannot use object of type DI\\Container as array 

So if I can't use unset, how do I remove the default error handler? I tried the following:
`unset($app->getContainer()->get('errorHandler'));`

But of course that doesn't make sense and I got the following error:

>  PHP Fatal error:  Can't use method return value in write context

Containers come with has() and get() and ContainerBuilder  has addDefinitions() but do they have remove() or removeDefinitions()?

When an error gets triggered it calls the handler here:

```
    protected function handlePhpError(Throwable $e, ServerRequestInterface $request, ResponseInterface $response)
    {
        $handler = 'phpErrorHandler';
        $params = [$request, $response, $e];
        if ($this->container->has($handler)) {
            $callable = $this->container->get($handler);
```

But I want this to evaluate to false:

`if ($this->container->has($handler)) {`

Is it doable with Slim-Bridge?

**Comment by mnapoli** [comment]
The error handler is configured in this repository, here: https://github.com/PHP-DI/Slim-Bridge/blob/master/src/config.php#L41
You can't remove that if you are using this project :( I hope you'll find a way to achieve what you are trying to do (customize the error handling I guess?) another way.

**Comment by booni3** [comment]
@adjenks Did you find a solution to this? I am trying to use Whoops with the slim-bridge but am having similar issues.

**Comment by mnapoli** [comment]
@booni3 What you could do is override the `'errorHandler'` container entry completely. That means that you have to redefine it though, depending of your level of confidence with Slim and PHP-DI it might not be easy.

**Comment by adjenks** [comment]
@booni3 , I believe I did as @mnapoli suggested and overwrote the 'errorHandler', 'phpErrorHandler', and 'notFoundHandler' keys in the configuration by passing a configuration array to `\DI\ContainerBuilder->addDefinitions();`

**Comment by ffgplaygiga** [comment]
$definitions = [
            'settings.displayErrorDetails' => true,
            'errorHandler' => function (ContainerInterface $container) {
                $logger = new Monolog\Logger('logger');
                $filename = __DIR__ . '/../logs/error.log';
                $stream = new Monolog\Handler\StreamHandler($filename, Monolog\Logger::DEBUG);
                $fingersCrossed = new Monolog\Handler\FingersCrossedHandler(
                    $stream, Monolog\Logger::ERROR);
                $logger->pushHandler($fingersCrossed);
                return new ErrorHandler($logger);
            }
]
