### ISSUE TITLE
Can't disable custom error handling when using Slim-Bridge

### ISSUE THREAD

**Issue by sbrl** [PHP-DI/Slim-Bridge#18]
If you're using this project in conjunction with Slim 3, you can't disable error handling. I'm having an issue where slim is eating exceptions and errors and emitting a generic error page - and nothing I do seems to make it emit a detailed error page instead. In addition, I can't disable this functionality either, which is really annoying! The best I can do is to re-throw the errors by including something like this in my dependency configuration file:

```php
"errorHandler" => function() {
	return function(Request $request, Response $response, Exception $error) {
		throw new RuntimeException("An error occurred - rethrowing", 0, $error);
	};
},
"phpErrorHandler" => function() {
	return function(Request $request, Response $response, Error $error) {
		throw new RuntimeException("An error occurred - rethrowing", 0, $error);
	};
}
```

...but even this isn't great, as it destroys the stack trace :-(

How can I get a useful error message out of slim 3 using this DI bridge, or at least disable the whole functionality entirely?

It seems like an essential part of any somewhat serious developer's toolbox is missing here.

**Comment by mnapoli** [comment]
Hi @sbrl, here is what I read on Slim's documentation: https://www.slimframework.com/docs/handlers/error.html

> The default error handler is very basic. It sets the Response status code to 500, it sets the Response content type to text/html, and appends a generic error message into the Response body.

> The default error handler can also include detailed error diagnostic information. To enable this you need to set the `displayErrorDetails` setting to true:

If you want to change the `displayErrorDetails` settings, have a look at the documentation: http://php-di.org/doc/frameworks/slim.html#configuring-slim

```php
return [
    'settings.displayErrorDetails' => true,
];
```

Does that answer your question?

**Comment by sbrl** [comment]
Yep, that appears to work! I think I must have missed that part of the documentation. It's all over the place , and I must have got confused. Thanks 😄

Perhaps it should be mentioned in more than one place?
