### ISSUE TITLE
Access config settings values into controller?

### ISSUE THREAD

**Issue by jokeronaldo** [PHP-DI/Slim-Bridge#19]
1. There is a way to access simple array raw values into controllers?
2. Alternatevely, there is a way to inject container into base class that will bt extended by other controllers?

**My settings.php**
```
<?php
return [
    'defaultCategoryId' => 1977697,
    'settings.displayErrorDetails' => true,
    'settings.database' => [
        'default' => [
            'driver'   => 'oracle',
            'host'     => '192.168.0.200',
            'database' => 'XE',
            'username' => 'root',
            'password' => 'pass',
            'prefix'   => '',
            'port'  => 1521
        ],
        'localmysql' => [
            'driver'   => 'mysql',
            'host'     => 'localhost',
            'database' => 'bridge',
            'username' => 'root',
            'password' => '',
            'prefix'   => '',
            'port'  => 3306
        ]
    ]
];
```

**My routes.php**
```
<?php
use \Psr\Http\Message\RequestInterface;
use \Psr\Http\Message\ResponseInterface;

// Root
$app->get('/', function (RequestInterface $request, ResponseInterface $response, $args) {
    return $response->withStatus(403)->write('Forbidden.');
});
$app->get("/test", ['App\Controllers\Bridge', 'test']);
```

**My Controller Bridge.php**
```
<?php
namespace App\Controllers;

use GuzzleHttp\Client;
use App\Models;
use App\Repositories;
use App\Helpers;
use function DI\get;

class Bridge extends Base
{
    protected $httpClient;
    protected $TgfproRepository;

    public function __construct(Repositories\Tgfpro $TgfproRepository)
    {
        $this->httpClient = new Client();
        $this->TgfproRepository = $TgfproRepository;
    }

    public function test()
    {
        echo get('defaultCategoryId');
    }
}
```

**So, when I run test endpoint I get an error:** Catchable fatal error: Object of class DI\Definition\EntryReference could not be converted to string in C:\xampp\htdocs\intelbrasonline-bridge\src\Controllers\Bridge.php on line ...

## First:
Well, the property is an object and when I try to var_dump this, it's is just a string reference.
I just want to catch the settings values inside controllers, just get the raw values.

If I inject the container into class I can easy access that values, but, it is the right way? There is any other method to do that?

## Second:
If it is mandatory to inject container to access settings values, there is a way to inject container into Base Controller? I mean, inject into base controller without doing parent::_construct() something like this into classic slim di container:

```
$container['Base'] = function ($c) {
    return new Base($c);
};
```

Thank you everyone.

**Comment by mnapoli** [comment]
Hi, to inject a value of the container you can do this:

```php
$container['Base'] = function ($c) {
    return new Base($c->get('defaultCategoryId'));
};
```

That way instead of injecting the whole container you inject only the value you want.

You should not use `DI\get()` outside of the PHP-DI configuration file, that function is a helper to declare definitions. It doesn't "get" the value from the container.

**Comment by jokeronaldo** [comment]
**Fatal error: Cannot use object of type DI\Container as array in C:\xampp\htdocs\intelbrasonline-bridge\src\dependencies.php on line 28**

Just can't use like classic slim di:
```
$container = $app->getContainer();

$container['Base'] = function ($c) {
    return new Base($c->get('defaultCategoryId'));
};
```

**Comment by mnapoli** [comment]
Oh ok sorry I copy-pasted your example without looking. Please read PHP-DI's documentation first because setting values in PHP-DI's container is the first step you need to learn: http://php-di.org/doc/

**Comment by jokeronaldo** [comment]
I already read, a lot of times, but I can't do what I'm trying to do.
Well, there is a way to inject container into base controller? I mean, everytime any controller extends base controller, the base controller will be extended with container injected it self.

**Comment by mikroware** [comment]
This might be a bit late, but stumbled on this issue when trying to do the same. At least, I think we have the same intention. I think in other words you want to inject a container item that cannot be type-hinted (like classes). Generally such an item would be a single element or an array of settings.

Currently in the docs there is an example on how to configure Twig with PHP-DI and the Slim-Bridge. Which is where I got my solution from as it showed how to type hint the whole container. This is what I ended up doing to inject some of my settings to the service.

```php
class PspService
{
  private $key;
  
  public function __construct(ContainerInterface $c)
  {
    $this->key = $c->get('settings.pspkey');
  }
}
```

**Comment by seugenev** [comment]
> This might be a bit late, but stumbled on this issue when trying to do the same. At least, I think we have the same intention. I think in other words you want to inject a container item that cannot be type-hinted (like classes). Generally such an item would be a single element or an array of settings.
> 
> Currently in the docs there is an example on how to configure Twig with PHP-DI and the Slim-Bridge. Which is where I got my solution from as it showed how to type hint the whole container. This is what I ended up doing to inject some of my settings to the service.
> 
> ```
> class PspService
> {
>   private $key;
>   
>   public function __construct(ContainerInterface $c)
>   {
>     $this->key = $c->get('settings.pspkey');
>   }
> }
> ```

could you provide the whole example of how to inject container from the moment of it creation ?
i have created a[ question on stackoverflow](https://stackoverflow.com/questions/56431520/php-di-how-to-access-container-definitions).

**Comment by mikroware** [comment]
I have provided an answer on your stackoverflow question. In short, as you are injecting the `Router` class in your `App` class, you can also profit from injection in the `Router` class. Just in the same way it is injected in the `App` class.

Then in the `__constructor` of the `Router` you can type hint the injection of the `ContainerInterface` like in my tiny example above.
