### ISSUE TITLE
Inject extra route params to controller?

### ISSUE THREAD

**Issue by AviBueno** [PHP-DI/Slim-Bridge#21]
First off, slick project - I'm lovin' it!

So, I inherited a Slim-Bride project and I'm trying to simplify it.
Let's take the login scenario for example.

**LoginController.php**:

    class LoginController {
        public function login( $userId, AuthService $authService, Response $response, $successUrl, $failUrl ) {
            if ( $authService->authenticate( $userId ) ) {
                return $response->withRedirect( $successUrl );
            }

            return $response->withRedirect( $failUrl );
        }
    }

**router.php**:

    $app->get('/login/{userId}', function( LoginController $loginController, $userId, AuthService $authService, Response $response, RouterInterface $router ) {
        $successUrl = $router->relativePathFor( 'login-success' );
        $failUrl = 'http://disney.com';
        return $loginController->login( $userId, $authService, $response, $successUrl, $failUrl );
    });

* Easy to see, DI doesn't come into play in all its glory here because any change to the login() method's params will require refactoring the route.

The following is the way to go, but it lacks the extra route parameters:

    $app->get('/login/{userId}', [ LoginController::class, 'login' ] );

So my question is if there's a way to achieve something like this:

    $app->get('/login/{userId}', \DI\method( [ LoginController::class, 'login' ] )
                        ->setParameter( 'successUrl', $router->relativePathFor( 'login-success' ) )
                        ->setParameter( 'failUrl', 'http://disney.com' )
                    );

As a similar use case, I'd like to be able to pass the page to be rendered to a ViewController:

    $app->get('/', \DI\method( [ ViewController::class, 'render' ] )->setParameter( 'filename', 'home.html' ) );
    $app->get('/search', \DI\method( [ ViewController::class, 'render' ] )->setParameter( 'filename', 'search_page.html' ) );
    $app->get('/blog', \DI\method( [ ViewController::class, 'render' ] )->setParameter( 'filename', 'blog_ext.html' ) );

So... is it possible?

**Comment by SergeAx** [comment]
This is not how dependency injection works. It's more something like this:

```php
class LoginController {
    private $router;
    private $authService;
    private $settings;
    public function __construct(Router $router, AuthService $authService, array $settings) {
    	$this->router = $router;
    	$this->authService = $authService;
    	$this->settings = $settings;
    }

    public function login( $userId, Response $response ) {
        if ( $authService->authenticate( $userId ) ) {
            return $response->withRedirect(
            	$this->router->relativePathFor( $this->settings['successRoute'] )
            );
        }
        return $response->withRedirect( $this->settings['failUrl'] );
    }
}
```

And in config.php:

```php
return [
    'settings.loginController' => [
        'sucessRoute' => 'login-success',
        'failUrl' => 'http://disney.com/',
    ],
    LoginController::class => DI\object()
        ->constructorParameter('settings', DI\get('settings.loginController')),
    AuthService::class => ... you should describe your service too
];
```

(please note that code above is ad-hoc and untested)

**Comment by AviBueno** [comment]
@SergeAx thank you. I am aware of the fact that I can pass it as part of the configuration. The drive for my question was to try and handle the route params locally inside the route.php file instead of involving another file.

One thought I had was to add a middleware to the route and push the urls as $request->withAttribute(...). This will keep everything inside the route file, but this seems somewhat of an overkill.

I thought there was a way to dynamically inject at the method level.
Perhaps there isn't.

**Comment by SergeAx** [comment]
In my opinion it is not a good idea to keep configuration settings (addresses to redirect user) and domain logic (routes) in a single location. This way you are piling up your dependencieis and will some day construct The God File, which is an antipattern to DI.

I understand, at the same time, that separating route's names and it's usage is not a best idea too, because you will need to change it in several files in case of refactoring. I had similar experiences and will try to think it through again. Right now I would only standartize outbound URLs like this:

```php
...
    'settings.loginController' => [
        'sucessUrl' => DI\get('router')->relativePathFor('login-success'),
        'failUrl' => 'http://disney.com/',
    ],
...
```

and decouple `LoginController` from `Router`.

**Comment by SergeAx** [comment]
Alas, I checked and this approach doesn't work. To decouple `LoginController` from `Router` one needs to create `LoginControllerFactory` and couple it with `Router` and `AuthService` :)

**Comment by AviBueno** [comment]
Thanks for the effort. I'll stick to your 'settings.loginController' suggestion for now.

**Comment by SergeAx** [comment]
There's this guy named Asperger, he just won't let some people left a job unfinished :)

Here's how it actually works:

```php

use Interop\Container\ContainerInterface as CI;
return [
...
    'settings.loginController' => function(CI $c) {
    	return [
    		'successUrl' => $c->get('router')->relativePathFor('login-success'),
    		'failUrl' => 'http://disney.com/',
    	];
    },
...
];
```

And you don't need a router inside controller.

**Comment by mnapoli** [comment]
Hi both,

I have to agree that it's a bit complicated. What @SergeAx suggests is a good solution, personally I would even simplify this further and put all the URL generation directly in the controler (i.e. not inject URLs). The controller will be doing a bit of work but IMO that's fine.

Anyway that's up to you :)

Closing but feel free to continue the discussion.

**Comment by SergeAx** [comment]
@mnapoli My understanding was that TS wanted to keep all his app's settings in one place and not spread it  evenly thru the code. I don't readily see how to extend this practice to Slim routes names, but it's more a Slim's problem.

By the way, I see this pattern in Slim-Bridge `config.php`:

```php
return [

    // Settings that can be customized by users
    'settings.httpVersion' => '1.1',
    'settings.responseChunkSize' => 4096,
    'settings.outputBuffering' => 'append',
    'settings.determineRouteBeforeAppMiddleware' => false,
    'settings.displayErrorDetails' => false,
    'settings.addContentLengthHeader' => true,
    'settings.routerCacheFile' => false,

    'settings' => [
        'httpVersion' => DI\get('settings.httpVersion'),
        'responseChunkSize' => DI\get('settings.responseChunkSize'),
        'outputBuffering' => DI\get('settings.outputBuffering'),
        'determineRouteBeforeAppMiddleware' => DI\get('settings.determineRouteBeforeAppMiddleware'),
        'displayErrorDetails' => DI\get('settings.displayErrorDetails'),
        'addContentLengthHeader' => DI\get('settings.addContentLengthHeader'),
        'routerCacheFile' => DI\get('settings.routerCacheFile'),
    ],
```

I actually used the same pattern in code for this topic:

```php
return [
...
    'settings.loginController.successUrl' => function(CI $c) {
        return $c->get('router')->relativePathFor('login-success');
    },
    'settings.loginController.failUrl' => 'http://disney.com/',

    'settings.loginController' => function(CI $c) {
    	return [
    	    'successUrl' => $c->get('settings.loginController.successUrl'),
    	    'failUrl' => $c->get('settings.loginController.failUrl'),
        ];
    },
...
];
```
but edited it for brevity and readability. And I thought about something like this:
```php
    'settings.loginController' => DI\settings(),
```

which will scan the container once for `'settings.loginController.*'` (asterisk excluding any subsequent points, so `settings.*` doesn't includes `settings.Level.Two`) and combine them into array. Is that actually possible in this exact notation, taking hint from PHP definitions array key, like `DI\object()`?

**Comment by mnapoli** [comment]
@SergeAx this would be technically possible but that sounds a bit too magic to me I think ;)

**Comment by manishmaharjan69051** [comment]
i want to have two group route ...lets say group 1 is admin and group 2 is user.
when i am in admin group, idont want admin to go to user route and when i am in user group i dont want to go to admin group route...is there any way...
