### ISSUE TITLE
Slim 4 support

### ISSUE THREAD

**Issue by SergeAx** [PHP-DI/Slim-Bridge#22]
Hello! Thank you for great project, I'm using it extensively and having a lot of fun an delight with all theese autowirings and nice config)

There is work in progress for Slim 4 for more than half a year:

https://github.com/slimphp/Slim/tree/4.x

Slim is going to keep it's honor of most interchangeble framework in PHP universe. PHP-DI\Slim-Bridge should definitely support new version, so I forked this repo and started to hack something together: 

https://github.com/SergeAx/Slim-Bridge/tree/dev-4x

Alas. I stumbled upon nasty error about 'calling non-static method statically':

https://travis-ci.org/SergeAx/Slim-Bridge/jobs/256378905

Maybe someone here more familiar with PHP-DI and Slim-Bridge can easily point out an error?

**Comment by mnapoli** [comment]
Hi @SergeAx, thanks for the kind words!

Supporting Slim 4 is definitely planned, thanks for getting the work started. Your branch looks fine, however the problem with that test is, I believe, that the `callableResolver` is not used anymore.

Maybe Slim 4 changed how callable are resolved?

**Comment by SergeAx** [comment]
If you check Travis log you'll see the error is in `src/ControllerInvoker.php:32`. Curiously, line 32 is just an `__invoke` [method declaration](https://github.com/SergeAx/Slim-Bridge/blob/dev-4x/src/ControllerInvoker.php#L32). It is also weird that PHPStorm debugger is unable to step into this call from here:

```php
$routeResponse = $handler($callable, $request, $response, $this->arguments);
```

([Slim\Route.php:327](https://github.com/slimphp/Slim/blob/4.x/Slim/Route.php#L327))

`$handler` is `DI\Bridge\Slim\ControllerInvoker` and `$callable` is `array('DI\Bridge\Slim\Test\Fixture\UserController', 'dashboard')`, so everything looks solid, but somehow it's not.

The only explanation I have is that PHP is trying to cast `array(2)` to `callable` and fails because an object is not instantiated? But this worked fine with Slim 3, and `Slim\Interfaces\InvocationStrategyInterface` haven't changed since.

**Comment by SergeAx** [comment]
Sorry for posting too soon. You were right: `Slim\Router` weren't  using `callableResolver` from container. After force set it via `setCallableResolver()` last test passed. You'll have PR in a minute, upstream branch name is up to you, `dev-4x` is first thing came to me.

**Comment by mnapoli** [comment]
Nice thanks!

**Comment by mnapoli** [comment]
Here is more information for Slim 4, they are planning to remove completely their container: https://github.com/slimphp/Slim/pull/2290#issuecomment-322184637

**Comment by mnapoli** [comment]
The PR has been merged, it seems that one course of action in this bridge would be to let PHP-DI create the Slim Application class. I haven't studied the details to see if it's the best yet.

**Comment by killua-eu** [comment]
Hey all, any news on the Slim 4 compatibility? Thanks!

**Comment by ghost** [comment]
Bump, would also like to know if this is still happening.

**Comment by mnapoli** [comment]
Given the discussion at https://github.com/slimphp/Slim/issues/2770 yes I think there would be value in writing a bridge that ports the current features.

I have no ETA at the moment, but I use both projects quite often so once I get my hands on Slim 4 I may get started.

**Comment by SergeAx** [comment]
Looks like https://github.com/slimphp/Slim-Skeleton for Slim 4 incorporated PHP-DI as a ЗЫК-compatible component, so we basically don't need slim-bridge for it anymore, right?

**Comment by mnapoli** [comment]
You might want it if you want to keep some features, for example auto-injecting services and parameters in controller parameters.

**Comment by mnapoli** [comment]
Current progress: #47
