### ISSUE TITLE
Add configuration to settings array

### ISSUE THREAD

**Issue by tomasruud** [PHP-DI/Slim-Bridge#23]
I'm trying to use Slim-Bridge and php-slim-whoops, together, but php-slim-whoops requires some debug settings set to true, like this:
```php
return [
    'settings' => [
        'displayErrorDetails' => true,
        'debug' => true
    ]
];
``` 
The problem is that when I'm using `addDefinitions()` with this config, it seems to override the entire `settings` array, rather than merging. Is this the desired behaviour, or is there a simple way to work around this?

**Comment by tomasruud** [comment]
Sorry, nevermind. This can be solved using PHP-DI functions like this: [http://php-di.org/doc/definition-overriding.html#arrays](http://php-di.org/doc/definition-overriding.html#arrays)

**Comment by mnapoli** [comment]
Hi, you can also use those configuration values directly instead of overwriting the whole array: https://github.com/PHP-DI/Slim-Bridge/blob/master/src/config.php#L18-L25

This is what is recommended in the documentation by the way: http://php-di.org/doc/frameworks/slim.html#configuring-slim

Hope that helps!

**Comment by tomasruud** [comment]
Yeah, I did see that. My problem was that the `debug` setting is not a part of the default Slim settings.

**Comment by mnapoli** [comment]
@tomasruud ah right! This is maybe a flag that was added not so long ago, if you want feel free to create a pull request to add it :)

**Comment by tomasruud** [comment]
Actually I think it was deprecated in Slim 3, so I guess there is no need to do it.

**Comment by niahoo** [comment]
I use the following pattern : 

```PHP
$app = new class() extends \DI\Bridge\Slim\App {
    protected function configureContainer(DI\ContainerBuilder $builder)
    {
        $settings = require __DIR__ . '/../src/settings.php';
        $settings = array_map('Di\add', $settings);
        $builder->addDefinitions($settings);
    }
};
```
~~Edit: no, it doesn't work, as `Di\add` does not seem to overwrite already existing definitions like `settings.displayErrorDetails`.~~

Edit 2: Actually it does overwrite as intended if I set it to `true` in the settings and var_dump the settings in a controller, but if I trigger an error in my code, the error handler is given `false` here : https://github.com/slimphp/Slim/blob/3.x/Slim/Handlers/AbstractError.php#L26 .

Thank you
