### ISSUE TITLE
'errorHandler' should get the `settings.outputBuffering` value

### ISSUE THREAD

**Issue by RyanNerd** [PHP-DI/Slim-Bridge#30]
Here: 
https://github.com/PHP-DI/Slim-Bridge/blob/master/src/config.php#L42

Should probably read:

`->constructor(DI\get('settings.displayErrorDetails'), DI\get('settings.outputBuffering')),`

**Comment by mnapoli** [comment]
Thanks, it seems this parameter was added in 3.9.0 (https://github.com/slimphp/Slim/commit/6f6af26e1dfccb168b2c28930d94de25c455dae8).

Feel free to send a pull request, since the parameter is optional everything still works as usual (nothing broke) so I'll add it to the end of my todo list ;)
