### ISSUE TITLE
PHP-DI 6 support with Slim 3?

### ISSUE THREAD

**Issue by exts** [PHP-DI/Slim-Bridge#32]
Notice that 6.0 is live and I'm wondering if there are any plans to support 6.0 with slim 3 & 4?

**Comment by mnapoli** [comment]
Hi, PHP-DI 6.0 is not yet stable. I think it will be easier to support Slim 4 with PHP-DI 6 because Slim 4 fixes some things in the container config that make a lot of sense with 6.0.

Anyway I think that's worth exploring, I'm focusing on finishing 6.0 first for now.

**Comment by mnapoli** [comment]
Done! I've released 2.0.0.
