### ISSUE TITLE
Possible changes to Slim 3.x that may conflict with PR#31

### ISSUE THREAD

**Issue by RyanNerd** [PHP-DI/Slim-Bridge#33]
This is just a heads up.
[This Slim PR](https://github.com/slimphp/Slim/pull/2337#pullrequestreview-78304772) hasn't been merged yet but it is likely.
If merged this may potentially cause issues with Slim-Bridge PR #31 (which is merged) -- the unit tests I wrote for PR #31 will most certainly fail.

**Comment by mnapoli** [comment]
Thanks for the heads up!

**Comment by RyanNerd** [comment]
@mnapoli https://github.com/slimphp/Slim/pull/2337#pullrequestreview-78304772 has been merged. This will possibly break PR #31. Either PR #31 should be reverted, or I can create a new PR that performs the code revert. Let me know which is easier/safer.

**Comment by mnapoli** [comment]
@RyanNerd since you are offering I'd be more confortable if you do it and have a look at the diff :) ? (I'm not 100% certain if it's a simple revert of the merge commit or if you have ideas on improving things a bit)

**Comment by RyanNerd** [comment]
@mnapoli I created a PR that addresses this issue.
