### ISSUE TITLE
Can't use $agrs = [] parameter

### ISSUE THREAD

**Issue by odahcam** [PHP-DI/Slim-Bridge#38]
Slim 3 allows the user to use a `$args= []` parameter where the route parameters are injected:
```php
class SomeController {
    function someAction($request, $response, $args = []) {}
}
```

In Slim-Bridge nothing is injected into the `$args` parameter.

**Comment by mnapoli** [comment]
No because the bridge works differently, you either inject each parameters explicitly (as a method parameter) or you get the argument from the route attributes.

**Comment by vikkio88** [comment]
@mnapoli could you explain this a bit better? with a code example maybe.


As I was saying in another comment, my current approach to extract args from route, since I am using an Callable class instead of controllers is the following

```php
private function getArgsFromRequest(RequestInterface $request): array
    {
        $attributes = $request->getAttributes();
        return isset($attributes["route"]) ? ($attributes["route"])->getArguments() : [];
    }

    public function __invoke(RequestInterface $request, ResponseInterface $response): ResponseInterface
    {
        $this->request = $request;
        $this->response = $response;
        $this->args = $this->getArgsFromRequest($request);
        return $this->execute();
    }
```

**Comment by mnapoli** [comment]
Please read: http://php-di.org/doc/frameworks/slim.html#controller-parameters Is that more clear with the documentation?

Can you show an example of one of your controller if that's not clear?

**Comment by vikkio88** [comment]
they are not controller, they are Actions (UseCase Pattern)
this for example https://github.com/vikkio88/slime/blob/master/Actions/Ping/PingGet.php
will be called like this
```php
$api->get('/ping', PingGet::class);
```

And slim usually does something like
```
$action = new Ping($container);
$action->__invoke($request,$response,$args);
```

within the ```invoke``` in my class I do a lot of thing, but the most important one is that ```performAction``` which needs to be specified in each action...

I solved it as I said above, but it feels ugly to have to create a middleware where to hardcode the parameters that you think it will be called... that is why I prefered the slim way of pushing $args array there.

I hope this does make sense

**Comment by mnapoli** [comment]
Oh you should definitely not store stuff in properties of your controller/action (this is roughly the same thing).

To be honest you are creating a framework on top of a framework, it's overcomplicating things.

**Comment by vikkio88** [comment]
from my point of view this allow me to be more DRY, I am just writing a single method definition and it will return with the responder the right json/xml whatever, rather than having repeat the same code over and over again.

**Comment by mnapoli** [comment]
DRY is not about code: http://verraes.net/2014/08/dry-is-about-knowledge/

But more concretely in your case you can write helper methods.

Anyway can you show an example of an action that uses parameters?

**Comment by vikkio88** [comment]
```php
<?php
namespace App\Actions\Podcast;
use App\Lib\Slime\RestAction\ApiAction;
use App\Models\Podcasts\Podcast;
class PodcastGetOne extends ApiAction
{
    protected function performAction()
    {
        $this->payload = Podcast::complete()
            ->where(
                'slug',
                $this->args['slug']
            )->first();
    }
}
```

that `$this-args` comes from the ```__invoke($req,$res,$arg)```

**Comment by vikkio88** [comment]
We are not here to speak about how I am using it anyway, what I am trying to say here is that **Slim-pimple** provided this nice functionality of injecting `$args` and with **php-di** bridge is not there anymore, and I was wondering if anyone has encountering it as a problem, and I proposed my solution. that is pretty much it :smile:

**Comment by odahcam** [comment]
I would like the injector to inject all my arguments into my `$args` parameter. 

Can it be a feature-request?

The injector could extract the arguments array from route and put them into the `$args` parameter when it's present.

**Comment by odahcam** [comment]
up

**Comment by mnapoli** [comment]
Here is a solution for you:

```php
<?php
namespace App\Actions\Podcast;
use App\Lib\Slime\RestAction\ApiAction;
use App\Models\Podcasts\Podcast;

class PodcastGetOne extends ApiAction
{
    public function performAction($slug)
    {
        $this->payload = Podcast::complete()
            ->where(
                'slug',
                $slug
            )->first();
    }
}
```

> I would like the injector to inject all my arguments into my $args parameter.
>
> Can it be a feature-request?

I'm sorry this is not how this bridge works and this is not a change that I'm planning to do.

**Comment by vikkio88** [comment]
that does look a bit ugly (apart from the fact that does not work as I am injecting on the Constructor), imagine that I will need more than one arguments, and imagine that some of them needs to have a fallback in case they are not specified.
It will quickly become something like
```php
function(Request $req, Twig $twig, $stuff, $thing, $otherStuff = null,$otherthing = 'fallback'){
}
```
instead of having an helper method around an array to do
```php
function whatevs(){
    $otherthing = $this->get('otherthing', 'fallback');
    ....
}
```
Using the ```$args``` array was way better to do so, and the only thing I am saying in here is:
Slim does inject ($req,$res,$args) by default. PHP-DI does not, it will be a nice to have, again just saying and I see that someone else agrees.

Again is just a feature request, not telling you off or expecting you to fix my small invokable class :smile: 

as I said in the first comment I fixed it retrieving the params from the route.

**Comment by odahcam** [comment]
Well, this would be nice because it can make the migration from that damn Pimple easier. The bridge is awesome btw.

Edit.: I should be really annoyed with Pimple, but shouldn't be talking like that, it still is a nice open source project.

**Comment by vikkio88** [comment]
to make my code that I suggested [here](https://github.com/PHP-DI/Slim-Bridge/issues/38#issuecomment-368844011) work again on SlimV4 you need to change `'route'` to `'__route__'`.
