### ISSUE TITLE
When I use v2.0 with slim/twig have some problem.

### ISSUE THREAD

**Issue by hanjing5024064** [PHP-DI/Slim-Bridge#41]
I just follow your doc on http://php-di.org/doc/frameworks/slim.html 
but I get this warning:
Argument 1 passed to DI\Definition\Source\DefinitionFile::{closure}() must implement interface Interop\Container\ContainerInterface, instance of DI\Container given

I think this your bridge's problem, can you help me?

**Comment by mnapoli** [comment]
Are you using the `Interop\Container\ContainerInterface` typehint in your config? container-interop support has been dropped in PHP-DI 6, you need to replace it with `Psr\Container\ContainerInterface`.

Let me know if it's not that.

**Comment by hanjing5024064** [comment]
It works, just use Psr\Container\ContainerInterface, thanks for your help.
I think you should put this in your doc. It will help:)

**Comment by mnapoli** [comment]
Thanks, it is covered here for the migration: http://php-di.org/doc/migration/6.0.html#container-interop-and-psr-11

And the doc was changed to use the Psr typehints: http://php-di.org/doc/php-definitions.html#factories
