### ISSUE TITLE
container method call() does not autowire.

### ISSUE THREAD

**Issue by adjenks** [PHP-DI/Slim-Bridge#48]
As described on this page: http://php-di.org/doc/container.html#call
Call should perform autowiring when the container has the available .

```php
$app->get('', function (Request $request, Response $response) {
	return $this->call(function(Request $request, Response $response){
		return $response;
	});
});
```
Results in:

> Unable to invoke the callable because no value was given for parameter 1 ($request)

Because get() correctly autowired, whereas call() did not.

**Comment by adjenks** [comment]
Type hinting does not work, however, this works:
```php
$app->get('', function (Request $request, Response $response) {
	return $this->call(function(Request $request, Response $response){
		return $response;
	},[\DI\get('response')]); // "dependency injection based on explicit definition"
});
```

**Comment by mnapoli** [comment]
Requests and responses are not services, they are not autowired.

In controllers (`get()` method) they are injected not as services, but with a specific feature of https://github.com/PHP-DI/Invoker.
