### ISSUE TITLE
example of how to add definition per module?

### ISSUE THREAD

**Issue by rabih9780** [PHP-DI/Slim-Bridge#50]
I am building an app that consist of multiple modules. I have a master file that contains all the definitions for the container.

But I want to have a definition file per module (override previously loaded definitions). is that possible with this library? any example on how to do that?

**Comment by mnapoli** [comment]
Hi, yes it is definitely possible. That's actually PHP-DI's main strength ;)

Have a look here: http://php-di.org/doc/definition-overriding.html

There is also https://github.com/PHP-DI/Kernel that may be helpful, but it isn't required to use this. I use it for my own projects mainly.
