### ISSUE TITLE
middleware in docs

### ISSUE THREAD

**Issue by zabakala** [PHP-DI/Slim-Bridge#59]
Hi. In your Readme.md there is the following example:

```
$app->add(function ($request, $response, $next) {
    $request = $request->withAttribute('name', 'Bob');
    return $next($request, $response);
});
```

... but it generates the following err:

_**Fatal error:** Uncaught ArgumentCountError: Too few arguments to function Closure::{closure}(), 2 passed in /.../vendor/slim/slim/Slim/MiddlewareDispatcher.php on line 283 and exactly 3 expected in..._

**Comment by mnapoli** [comment]
Hi, good catch!

Slim middlewares have indeed changed a little bit in the new version 4. Here are more details: https://www.slimframework.com/docs/v4/concepts/middleware.html

Would you be able to send a pull request to update the example?
