### ISSUE TITLE
proxy like access

### ISSUE THREAD

**Issue by zabakala** [PHP-DI/Slim-Bridge#60]
Hi. I would like a to ask a question. I would like to use a proxy pattern on a controller so that I can for example decorate/override methods (routes) invocations. However, anytime I try to implement such a proxy pattern, usually via a magic **__call()**, I end up being rejected via the following error stack:

`[route_methd_name] is not a callable. A __call() method exists but magic methods are not supported`

Is something like this really not possible?

**Comment by mnapoli** [comment]
Hi, it seems to be a limitation of the Slim framework here. I don't think there is anything we can do in this package.
