### ISSUE TITLE
Issue after upgrading to PHP-DI 6.2.1

### ISSUE THREAD

**Issue by Brammm** [PHP-DI/Slim-Bridge#63]
After upgrading to PHP-DI 6.2.1 in our Slim v3 project using the PHP-DI Slim bridge, we are suddenly getting the following error when compiling the container:

```
Class 'AssociativeArrayResolver' not found in /var/www/html/cache/CompiledContainer.php on line 1210
```

Checking the generated file, it does indeed look like it's not importing the proper class. I'm assuming it has something to do with the move to opis/closure. If there's anything I can do to help, I'd be happy to.

**Comment by and1truong** [comment]
Use this one: https://github.com/andytruong/Slim-Bridge/releases/tag/2.0.1

I can't see branch 2.x anymore

**Comment by mnapoli** [comment]
@andytruong thank you for your link, that sounds like a fairly simple fix 🤔  Would you be able to open a pull request to this project?

**Comment by and1truong** [comment]
@mnapoli I am happy to do that, but I can't see branch 2.x.

**Comment by mnapoli** [comment]
I've opened https://github.com/opis/closure/pull/72

**Comment by mnapoli** [comment]
Fixed in https://github.com/opis/closure/issues/70
