### ISSUE TITLE
php8 support?

### ISSUE THREAD

**Issue by jhmoon2000** [PHP-DI/Slim-Bridge#65]
php 8.0.0 is out now. Could you please update your project so that I can use php-di/slim-bridge?

**Comment by mnapoli** [comment]
https://github.com/PHP-DI/Slim-Bridge/releases/tag/3.1.0

**Comment by zabakala** [comment]
Hi. Just upgraded my app to PHP8 as well as slim-bridge to 3.1.0. The following code snippet worked under PHP7 but ceased to work with PHP8:

```
/**
  * @Inject
  * @var IFoo
  */
 private IFoo $foo;
```

The stack trace says:
_foo contains a non existent class "IFoo". Did you maybe forget to add a "use" statement for this annotation?_

The composer.json includes among other deps:
```
"php-di/php-di": "6.3.0"
"slim/slim": "~4.7"
"php-di/slim-bridge": "^3.1.0"
"doctrine/annotations": "^1.11"
```
