### ISSUE TITLE
PHP 8 update isn't working, see details...

### ISSUE THREAD

**Issue by kgrosvenor** [PHP-DI/Slim-Bridge#68]
I'm getting the error mentioned here: https://github.com/PHP-DI/PHP-DI/issues/727

Is there any chance we could provide a package update to php di 6.3.0?

**Comment by kgrosvenor** [comment]
Deprecated: Method ReflectionParameter::getClass() is deprecated in /var/www/html/vendor/php-di/php-di/src/Definition/Source/ReflectionBasedAutowiring.php on line 65

**Comment by mnapoli** [comment]
Have you tried upgrading your dependencies?

**Comment by kgrosvenor** [comment]
Apologies, yep that was it - damn lockfile! Thank you! @mnapoli
