### ISSUE TITLE
Bridge is no longer needed

### ISSUE THREAD

**Issue by jasny** [PHP-DI/Slim-Bridge#75]
Slim v4 supports dependency injection using a container via `AppFactory::setContainer($container)`. [See documentation](https://www.slimframework.com/docs/v4/concepts/di.html).

This project can be archived and the [PHP-DI documentation for Slim](https://php-di.org/doc/frameworks/slim.html) can be updated to match the Slim documentation.

**Comment by mnapoli** [comment]
Hi, it seems you missed this part from the docs:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/720328/178112120-6e302b2d-fc3a-4692-9542-dfae8523bdd0.png">

Is it still relevant? If Slim 4 does that automatically we can consider it, but I think the bridge is still relevant here.

**Comment by mr9d** [comment]
@mnapoli As I tested, DI in controllers is working fine with *php-di* itself, without *Slim-Bridge*. Am I missing some point why the documentation references it as an additional feature?

For reference, I've created a service class like this:
```
class TestService {
    public function getPongMessage() {
        return 'Pong';
    }
}
```

Then I've created controller like this:
```
class PingRoute
{
    private TestService $testService;

    public function __construct(TestService $testService) {
        $this->testService = $testService;
    }

    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $message = $this->testService->getPongMessage();
        $result = new ResponseWrapperDto(new MessageDto($message));
        $response->getBody()->write(json_encode($result));
        return $response->withHeader('Content-type', 'application/json');
    }
}
```

Here's how I connected the controller:
```
$app->get('/ping', PingRoute::class);
```

Here's how I instantiate my slim app with php-di:
```
$containerBuilder = new ContainerBuilder();
$container = $containerBuilder->build();
AppFactory::setContainer($container);
$app = AppFactory::create();
```

I assume DI works well with this setup based on a successful response.

**Comment by mnapoli** [comment]
You haven't tested all of this bridge's features. I'll keep this issue closed.

**Comment by mr9d** [comment]
@mnapoli you are absolutely right. Sorry for being off-topic. My point is documentation https://php-di.org/doc/frameworks/slim.html may contain some misleading information. Feature "controllers as services, allowing dependency injection in controllers" may require some clarification.
