### ISSUE TITLE
E_DEPRECATED warning on PHP 8.4+, release fix?

### ISSUE THREAD

**Issue by dzuelke** [PHP-DI/Slim-Bridge#92]
Using Slim-Bridge with PHP 8.4 causes the following warning:

```
PHP Deprecated:  DI\Bridge\Slim\Bridge::create(): Implicitly marking parameter $container as nullable is deprecated, the explicit nullable type must be used instead in …/src/Bridge.php on line 25
```

This is fixed by 69f5e9e7304bd3e2931b5517996282dfce40ad7e; would it be possible to tag a 3.4.1 release with that commit included?

**Comment by mnapoli** [comment]
Release done 👍
